site_name: My Book
nav:
  - Home: index.md
  - Chapter 1: chapter1.md
  - Chapter 2: chapter2.md
  - Chapter 3: chapter3.md
theme:
  name: readthedocs
plugins:
  - search
  - include-markdown:
      encoding: utf-8
      dedent: true